version: "3.4"

services:
    tomtom2komoot:
        image: tomtom2komoot
        build:
            context: .
            dockerfile: prod.Dockerfile
        container_name: tomtom2komoot
        restart: always
        volumes:
            - /home/christian/Software/TomTom2Komoot/logs:/app/logs