version: "3.4"

services:
    tomtom2komoot:
        image: tomtom2komoot
        build:
            context: .
            dockerfile: prod.Dockerfile
        container_name: tomtom2komoot
        env_file: 
            - .env
        volumes:
            - /home/christian/Software/logs/TomTom2Komoot:/app/logs